### ISSUE TITLE
new name for pyTickleTickle

### ISSUE THREAD

**Issue by rxa254** [kevinkuns/qlance#6]
- Looper
- OptoLoop
- MIMO Feedback tool
- Interferometer Loop Calculator
- Loop Analysis Toolkit Helper (LATHE)
- INterferometer Calculator (INCA)
- Phrission
- Everything Is Connected
- Feedback Loop And Noise Calculation Engine (FLANCE)

**Comment by aa158** [comment]
pIGO
optomech
optipy
pyoptics
qom (quantum optomechanics)
gwoptics (where is that website name from anyway)
metroptical
metroptic

**Comment by jrollins** [comment]
QUAntum Loop Cavity Opto Mechanics (QUALCOM)
Cavity Opto Mechanics LOop Calculator (COMLOC)

**Comment by kevinkuns** [comment]
PyTickle -> QLANCE

**Comment by rxa254** [comment]
pronounced as "Clancy"
